/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import data.ActionsBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author fkissoum
 */
public class GestionVueAbstraite extends javax.swing.JFrame {

    /**
     * Creates new form Vue
     */
    public GestionVueAbstraite() {
      
        initComponents();
        this.setVisible(true);
        
        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogQuitter = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        buttonQuitterOui = new javax.swing.JButton();
        buttonQuitterNon = new javax.swing.JButton();
        dialogProgrammeurPasTrouvé = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        buttonOKIntrouvable = new javax.swing.JButton();
        ajoutRéussi = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        ajoutRéussiOK = new javax.swing.JButton();
        ajoutEchec = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        ajoutEchecOK = new javax.swing.JButton();
        suppressionRéussie = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        suppressionRéussieOK = new javax.swing.JButton();
        suppressionEchec = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        suppressionEchecOK = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        affichageProgrammeurs = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProgrammeur_bis = new javax.swing.JMenu();
        menuAfficher_bis = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemModifier_bis = new javax.swing.JMenuItem();
        itemSupprimer_bis = new javax.swing.JMenuItem();
        itemAjouter_bis = new javax.swing.JMenuItem();
        menuActions_bis = new javax.swing.JMenu();
        Quitter_bis = new javax.swing.JMenuItem();
        checkbox1 = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();
        textBoxNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textBoxAdresse = new javax.swing.JTextField();
        textBoxRespo = new javax.swing.JTextField();
        textBoxHobby = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textBoxPrénom = new javax.swing.JTextField();
        textBoxPseudo = new javax.swing.JTextField();
        jour_naissance = new javax.swing.JTextField();
        jour_embauche = new javax.swing.JTextField();
        comboBoxNaiss = new javax.swing.JComboBox<>();
        comboBoxEmb = new javax.swing.JComboBox<>();
        année_naissance = new javax.swing.JTextField();
        année_embauche = new javax.swing.JTextField();
        textBoxMatricule = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonRechercher = new javax.swing.JButton();
        buttonRéinitialiser = new javax.swing.JButton();
        buttonValider = new javax.swing.JButton();
        buttonAnnuler = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuProgrammeur = new javax.swing.JMenu();
        menuAfficher = new javax.swing.JMenu();
        itemTout = new javax.swing.JMenuItem();
        itemModifier = new javax.swing.JMenuItem();
        itemSupprimer = new javax.swing.JMenuItem();
        menuItemAjouter = new javax.swing.JMenuItem();
        menuActions = new javax.swing.JMenu();
        Quitter = new javax.swing.JMenuItem();

        dialogQuitter.setMinimumSize(new java.awt.Dimension(404, 164));
        dialogQuitter.setResizable(false);

        jLabel9.setText("Vérification");

        buttonQuitterOui.setText("Oui");
        buttonQuitterOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitterOuiActionPerformed(evt);
            }
        });

        buttonQuitterNon.setText("Non");
        buttonQuitterNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitterNonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogQuitterLayout = new javax.swing.GroupLayout(dialogQuitter.getContentPane());
        dialogQuitter.getContentPane().setLayout(dialogQuitterLayout);
        dialogQuitterLayout.setHorizontalGroup(
            dialogQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogQuitterLayout.createSequentialGroup()
                .addGroup(dialogQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogQuitterLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogQuitterLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(buttonQuitterOui)
                        .addGap(63, 63, 63)
                        .addComponent(buttonQuitterNon)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        dialogQuitterLayout.setVerticalGroup(
            dialogQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogQuitterLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogQuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonQuitterOui)
                    .addComponent(buttonQuitterNon))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        dialogProgrammeurPasTrouvé.setMinimumSize(new java.awt.Dimension(404, 164));

        jLabel11.setText("Programmeur introuvable");

        buttonOKIntrouvable.setText("OK");
        buttonOKIntrouvable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKIntrouvableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogProgrammeurPasTrouvéLayout = new javax.swing.GroupLayout(dialogProgrammeurPasTrouvé.getContentPane());
        dialogProgrammeurPasTrouvé.getContentPane().setLayout(dialogProgrammeurPasTrouvéLayout);
        dialogProgrammeurPasTrouvéLayout.setHorizontalGroup(
            dialogProgrammeurPasTrouvéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogProgrammeurPasTrouvéLayout.createSequentialGroup()
                .addGroup(dialogProgrammeurPasTrouvéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogProgrammeurPasTrouvéLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogProgrammeurPasTrouvéLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(buttonOKIntrouvable)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        dialogProgrammeurPasTrouvéLayout.setVerticalGroup(
            dialogProgrammeurPasTrouvéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogProgrammeurPasTrouvéLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOKIntrouvable)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        ajoutRéussi.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ajoutRéussi.setTitle("Succès");
        ajoutRéussi.setMinimumSize(new java.awt.Dimension(404, 164));
        ajoutRéussi.setPreferredSize(new java.awt.Dimension(404, 164));
        ajoutRéussi.setResizable(false);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ajout réussi");

        ajoutRéussiOK.setText("OK");
        ajoutRéussiOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutRéussiOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajoutRéussiLayout = new javax.swing.GroupLayout(ajoutRéussi.getContentPane());
        ajoutRéussi.getContentPane().setLayout(ajoutRéussiLayout);
        ajoutRéussiLayout.setHorizontalGroup(
            ajoutRéussiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutRéussiLayout.createSequentialGroup()
                .addGroup(ajoutRéussiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutRéussiLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(ajoutRéussiOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajoutRéussiLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        ajoutRéussiLayout.setVerticalGroup(
            ajoutRéussiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutRéussiLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajoutRéussiOK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        ajoutRéussi.getAccessibleContext().setAccessibleName("");

        ajoutEchec.setTitle("Echec");
        ajoutEchec.setMinimumSize(new java.awt.Dimension(460, 201));
        ajoutEchec.setResizable(false);

        jLabel13.setText("Ajout échoué");

        ajoutEchecOK.setText("OK");
        ajoutEchecOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutEchecOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajoutEchecLayout = new javax.swing.GroupLayout(ajoutEchec.getContentPane());
        ajoutEchec.getContentPane().setLayout(ajoutEchecLayout);
        ajoutEchecLayout.setHorizontalGroup(
            ajoutEchecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutEchecLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(ajoutEchecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(ajoutEchecLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ajoutEchecOK)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        ajoutEchecLayout.setVerticalGroup(
            ajoutEchecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutEchecLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ajoutEchecOK)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        suppressionRéussie.setTitle("Echec");
        suppressionRéussie.setMinimumSize(new java.awt.Dimension(404, 164));
        suppressionRéussie.setResizable(false);

        jLabel14.setText("Suppression réussie ! ");

        suppressionRéussieOK.setText("OK");

        javax.swing.GroupLayout suppressionRéussieLayout = new javax.swing.GroupLayout(suppressionRéussie.getContentPane());
        suppressionRéussie.getContentPane().setLayout(suppressionRéussieLayout);
        suppressionRéussieLayout.setHorizontalGroup(
            suppressionRéussieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppressionRéussieLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(164, 164, 164))
            .addGroup(suppressionRéussieLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(suppressionRéussieOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        suppressionRéussieLayout.setVerticalGroup(
            suppressionRéussieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppressionRéussieLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suppressionRéussieOK)
                .addGap(57, 57, 57))
        );

        suppressionEchec.setTitle("Echec");
        suppressionEchec.setMinimumSize(new java.awt.Dimension(404, 164));
        suppressionEchec.setResizable(false);

        jLabel15.setText("Suppression échouée");

        suppressionEchecOK.setText("OK");

        javax.swing.GroupLayout suppressionEchecLayout = new javax.swing.GroupLayout(suppressionEchec.getContentPane());
        suppressionEchec.getContentPane().setLayout(suppressionEchecLayout);
        suppressionEchecLayout.setHorizontalGroup(
            suppressionEchecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppressionEchecLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel15)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppressionEchecLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(suppressionEchecOK)
                .addGap(209, 209, 209))
        );
        suppressionEchecLayout.setVerticalGroup(
            suppressionEchecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppressionEchecLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(suppressionEchecOK)
                .addGap(62, 62, 62))
        );

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(825, 494));

        affichageProgrammeurs.setColumns(20);
        affichageProgrammeurs.setRows(5);
        jScrollPane1.setViewportView(affichageProgrammeurs);

        menuProgrammeur_bis.setText("Programmeur");

        menuAfficher_bis.setText("Afficher");

        jMenuItem1.setText("Tout");
        menuAfficher_bis.add(jMenuItem1);

        menuProgrammeur_bis.add(menuAfficher_bis);

        itemModifier_bis.setText("Modifier");
        itemModifier_bis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModifier_bisActionPerformed(evt);
            }
        });
        menuProgrammeur_bis.add(itemModifier_bis);

        itemSupprimer_bis.setText("Supprimer");
        itemSupprimer_bis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupprimer_bisActionPerformed(evt);
            }
        });
        menuProgrammeur_bis.add(itemSupprimer_bis);

        itemAjouter_bis.setText("Ajouter");
        itemAjouter_bis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAjouter_bisActionPerformed(evt);
            }
        });
        menuProgrammeur_bis.add(itemAjouter_bis);

        jMenuBar1.add(menuProgrammeur_bis);

        menuActions_bis.setText("Action");

        Quitter_bis.setText("Quitter");
        Quitter_bis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitter_bisActionPerformed(evt);
            }
        });
        menuActions_bis.add(Quitter_bis);

        jMenuBar1.add(menuActions_bis);

        jFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestProg");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(825, 494));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nom");

        textBoxNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxNomActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Adresse");

        textBoxHobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxHobbyActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Responsable");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hobby");

        jLabel5.setText("Prénom");

        jLabel6.setText("Pseudo");

        jLabel7.setText("Date de naissance");

        jLabel8.setText("Date d'embauche");

        comboBoxNaiss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboBoxNaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNaissActionPerformed(evt);
            }
        });

        comboBoxEmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboBoxEmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEmbActionPerformed(evt);
            }
        });

        année_naissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                année_naissanceActionPerformed(evt);
            }
        });

        textBoxMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxMatriculeActionPerformed(evt);
            }
        });

        jLabel10.setText("Matricule");

        buttonRechercher.setText("Rechercher");
        buttonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRechercherActionPerformed(evt);
            }
        });

        buttonRéinitialiser.setText("Réinitialiser");
        buttonRéinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRéinitialiserActionPerformed(evt);
            }
        });

        buttonValider.setText("Valider");
        buttonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderActionPerformed(evt);
            }
        });

        buttonAnnuler.setText("Annuler");

        menuProgrammeur.setText("Programmeur");

        menuAfficher.setText("Afficher");

        itemTout.setText("Tout");
        itemTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemToutActionPerformed(evt);
            }
        });
        menuAfficher.add(itemTout);

        menuProgrammeur.add(menuAfficher);

        itemModifier.setText("Modifier");
        itemModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModifierActionPerformed(evt);
            }
        });
        menuProgrammeur.add(itemModifier);

        itemSupprimer.setText("Supprimer");
        itemSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupprimerActionPerformed(evt);
            }
        });
        menuProgrammeur.add(itemSupprimer);

        menuItemAjouter.setText("Ajouter");
        menuItemAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjouterActionPerformed(evt);
            }
        });
        menuProgrammeur.add(menuItemAjouter);

        menuBar.add(menuProgrammeur);

        menuActions.setText("Actions");

        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });
        menuActions.add(Quitter);

        menuBar.add(menuActions);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBoxNom)
                    .addComponent(textBoxAdresse)
                    .addComponent(textBoxRespo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(textBoxHobby))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textBoxPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBoxPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jour_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jour_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAnnuler)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBoxNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(année_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(année_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(187, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBoxMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(buttonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(buttonRéinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBoxMatricule)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textBoxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textBoxPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textBoxAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textBoxPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textBoxRespo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(jour_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(année_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxHobby, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jour_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(année_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRechercher)
                    .addComponent(buttonRéinitialiser)
                    .addComponent(buttonValider)
                    .addComponent(buttonAnnuler))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void textBoxNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxNomActionPerformed

    private void textBoxHobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxHobbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxHobbyActionPerformed

    private void comboBoxNaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNaissActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_comboBoxNaissActionPerformed

    private void année_naissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_année_naissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_année_naissanceActionPerformed

    private void itemSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSupprimerActionPerformed
        buttonRechercher.setEnabled(false);
        buttonRéinitialiser.setEnabled(false);
        textBoxNom.setEditable(false);
        textBoxPrénom.setEditable(false);
        textBoxRespo.setEditable(false);
        textBoxPseudo.setEditable(false);
        textBoxHobby.setEditable(false);
        textBoxAdresse.setEditable(false);
        jour_naissance.setEditable(false);
        jour_embauche.setEditable(false);
        année_naissance.setEditable(false);
        année_embauche.setEditable(false);
        comboBoxNaiss.setEditable(false);
        comboBoxEmb.setEditable(false);
        this.setVisible(true);
        ActionListener l = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource()==buttonValider)
                {
                    
                    if(evt.getSource()==itemSupprimer || evt.getSource()==itemSupprimer_bis)
                    {
                        
                    ActionsBD dt = new ActionsBD();
                   
                    textBoxNom.setText("");
                    textBoxPrénom.setText("");
                    textBoxRespo.setText("");
                    textBoxPseudo.setText("");
                    textBoxHobby.setText("");
                    jour_naissance.setText("");
                    jour_embauche.setText("");
                    année_naissance.setText("");
                    année_embauche.setText("");
                    textBoxAdresse.setText("");
                    comboBoxNaiss.setSelectedIndex(1);
                    comboBoxEmb.setSelectedIndex(1);
                   
                    
                    int truc=dt.supprimerProgrammeurs(textBoxMatricule.getText());
                    System.out.println("truc supprimer : " + truc);
                    if(truc==0 || truc==-2)
                    {
                        suppressionEchec.setVisible(true);
                        
                        
                    }
                    else
                    {
                        suppressionRéussie.setVisible(true);
                    }
                    
                    }
                }
            }
        };
        
        buttonValider.addActionListener(l);
    }//GEN-LAST:event_itemSupprimerActionPerformed

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Quitter)
        {
            dialogQuitter.setTitle("Voulez-vous vraiment quitter? ");
            setBounds(10, 10, 600, 300);
            dialogQuitter.setVisible(true);
        }
        
        
    }//GEN-LAST:event_QuitterActionPerformed

    private void comboBoxEmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEmbActionPerformed
        // TODO add your handling code here:
  
        
    }//GEN-LAST:event_comboBoxEmbActionPerformed

    private void itemToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemToutActionPerformed
        // TODO add your handling code here:
        JPanel pane = new JPanel();
        //JFrame frame = new JFrame();
        //frame.setSize(220, 220);
        if(evt.getSource()== itemTout)
        {
        jFrame1.setTitle("GestProg");
        this.setVisible(false);
        jFrame1.setVisible(true);
        ActionsBD dt = new ActionsBD();
        affichageProgrammeurs.setText(dt.afficherProgrammeurs());
        setDefaultCloseOperation(EXIT_ON_CLOSE); // Fermeture fenêtre = arrêt de l'application 
        
        }
        
        /*this.setVisible(true);
        JTextArea zoneAffichageProgrammeurs;      
        zoneAffichageProgrammeurs = new JTextArea(50, 50);
        JScrollPane scroll= new JScrollPane(zoneAffichageProgrammeurs);   
        
        pane.add(scroll);
        this.setVisible(true);
        this.setTitle("GesProg");
        setBounds(10, 10, 600, 300);

        this.add(pane);
        
        
        if (evt.getSource() == itemTout) {
            ActionsBD dt = new ActionsBD();
            this.setContentPane(pane);
            String contenuTextArea;
            contenuTextArea = dt.afficherProgrammeurs();
            zoneAffichageProgrammeurs.setText(contenuTextArea);
            dt.fermerRessources();
            
        }
        */
    }//GEN-LAST:event_itemToutActionPerformed

    private void textBoxMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxMatriculeActionPerformed

    private void itemModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModifierActionPerformed
        // TODO add your handling code here:
        buttonRechercher.setEnabled(true);
        buttonRéinitialiser.setEnabled(true);
         this.setVisible(true);
         textBoxNom.setEditable(true);
         textBoxPrénom.setEditable(true);
         textBoxRespo.setEditable(true);
         textBoxPseudo.setEditable(true);
         textBoxHobby.setEditable(true);
         textBoxAdresse.setEditable(true);
         jour_naissance.setEditable(true);
         jour_embauche.setEditable(true);
        année_naissance.setEditable(true);
        année_embauche.setEditable(true);
        comboBoxNaiss.setEditable(true);
        comboBoxEmb.setEditable(true);
        ActionListener l = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource()==buttonValider)
                {
                    
                    if(evt.getSource()==itemModifier || evt.getSource()==itemModifier_bis)
                    {
                        
                    ActionsBD dt = new ActionsBD();
                    String nouvelleDateNaiss = année_naissance.getText() +"-"+ comboBoxNaiss.getSelectedItem()+"-"+jour_naissance.getText();
                    String nouvelleDateEmb = année_embauche.getText()+"-"+comboBoxEmb.getSelectedItem()+"-"+jour_embauche.getText();
                    dt.modifierProgrammeurs(textBoxMatricule.getText(), textBoxNom.getText(), textBoxPrénom.getText(), textBoxHobby.getText(), textBoxRespo.getText(), textBoxPseudo.getText(), nouvelleDateNaiss, nouvelleDateEmb, textBoxAdresse.getText());
                    }
                }
            }
        };
        
        buttonValider.addActionListener(l);
        
    }//GEN-LAST:event_itemModifierActionPerformed

    
    
    private void menuItemAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjouterActionPerformed
      
            
        // TODO add your handling code here:
        buttonRechercher.setEnabled(false);
        buttonRéinitialiser.setEnabled(true);
        textBoxNom.setEditable(true);
        textBoxPrénom.setEditable(true);
        textBoxRespo.setEditable(true);
        textBoxPseudo.setEditable(true);
        textBoxHobby.setEditable(true);
        textBoxAdresse.setEditable(true);
        jour_naissance.setEditable(true);
        jour_embauche.setEditable(true);
        année_naissance.setEditable(true);
        année_embauche.setEditable(true);
        comboBoxNaiss.setEditable(true);
        comboBoxEmb.setEditable(true);
        
        ActionListener l;
        l = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource()==buttonValider)
                {
                    
                    if(evt.getSource()==menuItemAjouter || evt.getSource()==itemAjouter_bis)
                    {
                        
                        
                        ActionsBD dt = new ActionsBD();
                        String nouvelleDateNaiss = année_naissance.getText() +"-"+ comboBoxNaiss.getSelectedItem()+"-"+jour_naissance.getText();
                        String nouvelleDateEmb = année_embauche.getText()+"-"+comboBoxEmb.getSelectedItem()+"-"+jour_embauche.getText();
                        int truc=dt.ajouterProgrammeurs(textBoxMatricule.getText(), textBoxNom.getText(), textBoxPrénom.getText(), textBoxHobby.getText(), textBoxRespo.getText(), textBoxPseudo.getText(), nouvelleDateNaiss, nouvelleDateEmb, textBoxAdresse.getText());
                        System.out.println("truc ajout : " + truc);
                        if(truc==1)
                        {
                            ajoutRéussi.setVisible(true);
                            jLabel12.setText("Ajout réussi!");
                            ajoutRéussi.setTitle("Succès");
                        }
                        else if(truc==0 || truc==-1)
                        {
                            ajoutEchec.setVisible(true);
                        }
                        
                    }
                }
            }
        };
        
        buttonValider.addActionListener(l);
        
        
    }//GEN-LAST:event_menuItemAjouterActionPerformed

    private void buttonQuitterOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitterOuiActionPerformed
               
        
        if(evt.getSource()==buttonQuitterOui)
            {
                
                this.dispose();
                jFrame1.dispose();
                dialogQuitter.dispose();
            }
          
    }//GEN-LAST:event_buttonQuitterOuiActionPerformed

    private void buttonQuitterNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitterNonActionPerformed
       
        if(evt.getSource()==buttonQuitterNon)
       {
           dialogQuitter.dispose();
           
       }
    }//GEN-LAST:event_buttonQuitterNonActionPerformed

    private void buttonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRechercherActionPerformed

        // TODO add your handling code here:
        
        if(evt.getSource()==buttonRechercher)
        {
            ActionsBD dt = new ActionsBD();
            ArrayList <String> result=new ArrayList <String> ();
            
           result=dt.rechercherProgrammeurs(textBoxMatricule.getText());
           if(result.size()==0)
           {
               dialogProgrammeurPasTrouvé.setTitle("Erreur");
               dialogProgrammeurPasTrouvé.setVisible(true);
               
           } 
           
           textBoxNom.setText(result.get(0));
           textBoxPrénom.setText(result.get(1));
           textBoxHobby.setText(result.get(5));
           textBoxRespo.setText(result.get(4));
           textBoxPseudo.setText(result.get(3));
           jour_naissance.setText(result.get(6));
           année_naissance.setText(result.get(8));
           jour_embauche.setText(result.get(9));
           année_embauche.setText(result.get(11));
           comboBoxNaiss.setSelectedItem(result.get(7));
           comboBoxEmb.setSelectedItem(result.get(10));
           textBoxAdresse.setText(result.get(2));
           
           
           
           
        }
    }//GEN-LAST:event_buttonRechercherActionPerformed

    private void buttonOKIntrouvableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKIntrouvableActionPerformed
        if(evt.getSource()==buttonOKIntrouvable)
        {
            dialogProgrammeurPasTrouvé.dispose();
        }
    }//GEN-LAST:event_buttonOKIntrouvableActionPerformed

    private void buttonRéinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRéinitialiserActionPerformed
        // TODO add your handling code here:
        textBoxMatricule.setText("");
        textBoxNom.setText("");
        textBoxPrénom.setText("");
        textBoxRespo.setText("");
        textBoxPseudo.setText("");
        textBoxHobby.setText("");
        jour_naissance.setText("");
        jour_embauche.setText("");
        année_naissance.setText("");
        année_embauche.setText("");
        textBoxAdresse.setText("");
        comboBoxNaiss.setSelectedIndex(1);
        comboBoxEmb.setSelectedIndex(1);
        
    }//GEN-LAST:event_buttonRéinitialiserActionPerformed

    private void buttonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderActionPerformed
  
       
    }//GEN-LAST:event_buttonValiderActionPerformed

    private void ajoutEchecOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutEchecOKActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==ajoutEchecOK)
        {
            jFrame1.dispose();
        }
        
    }//GEN-LAST:event_ajoutEchecOKActionPerformed

    private void itemSupprimer_bisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSupprimer_bisActionPerformed
        // TODO add your handling code here:
         if(evt.getSource()==itemSupprimer_bis)
        {
            this.setVisible(true);
            jFrame1.setVisible(false);
            itemSupprimerActionPerformed(evt);
            
           // GestionVueAbstraite.setDefaultLookAndFeelDecorated(true);
          
        }
    }//GEN-LAST:event_itemSupprimer_bisActionPerformed

    private void itemModifier_bisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModifier_bisActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==itemModifier_bis)
        {
            this.setVisible(true);
            jFrame1.setVisible(false);
            itemModifierActionPerformed(evt);
           // GestionVueAbstraite.setDefaultLookAndFeelDecorated(true);
          
        }
    }//GEN-LAST:event_itemModifier_bisActionPerformed

    private void itemAjouter_bisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAjouter_bisActionPerformed
        // TODO add your handling code here:
         if(evt.getSource()==itemAjouter_bis)
        {
            this.setVisible(true);
            jFrame1.setVisible(false);
            menuItemAjouterActionPerformed(evt);
            
           // GestionVueAbstraite.setDefaultLookAndFeelDecorated(true);
          
        }
    }//GEN-LAST:event_itemAjouter_bisActionPerformed

    private void ajoutRéussiOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutRéussiOKActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==ajoutRéussiOK)
        {
            jFrame1.dispose();
        }
    }//GEN-LAST:event_ajoutRéussiOKActionPerformed

    private void Quitter_bisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitter_bisActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Quitter_bis)
        {
            dialogQuitter.setTitle("Voulez-vous vraiment quitter? ");
            setBounds(10, 10, 600, 300);
            dialogQuitter.setVisible(true);
        }
    }//GEN-LAST:event_Quitter_bisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVueAbstraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVueAbstraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVueAbstraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVueAbstraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionVueAbstraite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Quitter;
    private javax.swing.JMenuItem Quitter_bis;
    private javax.swing.JTextArea affichageProgrammeurs;
    private javax.swing.JDialog ajoutEchec;
    private javax.swing.JButton ajoutEchecOK;
    private javax.swing.JDialog ajoutRéussi;
    private javax.swing.JButton ajoutRéussiOK;
    private javax.swing.JTextField année_embauche;
    private javax.swing.JTextField année_naissance;
    private javax.swing.JButton buttonAnnuler;
    private javax.swing.JButton buttonOKIntrouvable;
    private javax.swing.JButton buttonQuitterNon;
    private javax.swing.JButton buttonQuitterOui;
    private javax.swing.JButton buttonRechercher;
    private javax.swing.JButton buttonRéinitialiser;
    private javax.swing.JButton buttonValider;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JComboBox<String> comboBoxEmb;
    private javax.swing.JComboBox<String> comboBoxNaiss;
    private javax.swing.JDialog dialogProgrammeurPasTrouvé;
    private javax.swing.JDialog dialogQuitter;
    private javax.swing.JMenuItem itemAjouter_bis;
    private javax.swing.JMenuItem itemModifier;
    private javax.swing.JMenuItem itemModifier_bis;
    private javax.swing.JMenuItem itemSupprimer;
    private javax.swing.JMenuItem itemSupprimer_bis;
    private javax.swing.JMenuItem itemTout;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jour_embauche;
    private javax.swing.JTextField jour_naissance;
    private javax.swing.JMenu menuActions;
    private javax.swing.JMenu menuActions_bis;
    private javax.swing.JMenu menuAfficher;
    private javax.swing.JMenu menuAfficher_bis;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAjouter;
    private javax.swing.JMenu menuProgrammeur;
    private javax.swing.JMenu menuProgrammeur_bis;
    private javax.swing.JDialog suppressionEchec;
    private javax.swing.JButton suppressionEchecOK;
    private javax.swing.JDialog suppressionRéussie;
    private javax.swing.JButton suppressionRéussieOK;
    private javax.swing.JTextField textBoxAdresse;
    private javax.swing.JTextField textBoxHobby;
    private javax.swing.JTextField textBoxMatricule;
    private javax.swing.JTextField textBoxNom;
    private javax.swing.JTextField textBoxPrénom;
    private javax.swing.JTextField textBoxPseudo;
    private javax.swing.JTextField textBoxRespo;
    // End of variables declaration//GEN-END:variables
}
